
import React from 'react';
import { Rocket, GraduationCap, Users, Zap } from 'lucide-react';

const MarketCard = ({ icon: Icon, title, description, colorClass }: any) => (
  <div className="glass p-10 rounded-[40px] border-white/5 hover:border-white/20 transition-all hover:-translate-y-2 group">
    <div className={`w-14 h-14 rounded-2xl flex items-center justify-center mb-8 ${colorClass}`}>
      <Icon className="w-7 h-7 text-white" />
    </div>
    <h3 className="text-2xl font-bold mb-4 font-space">{title}</h3>
    <p className="text-gray-400 leading-relaxed text-sm">
      {description}
    </p>
  </div>
);

const TargetMarkets: React.FC = () => {
  return (
    <section className="py-24 relative">
      <div className="container mx-auto px-6">
        <div className="flex flex-col md:flex-row justify-between items-end gap-8 mb-20">
          <div className="max-w-xl">
            <h2 className="text-4xl md:text-5xl font-bold font-space tracking-tight mb-4">Built for the Builders</h2>
            <p className="text-gray-400">Aether isn't just a calling tool—it's the nervous system for your most ambitious projects.</p>
          </div>
          <div className="hidden md:block">
            <span className="text-xs font-mono text-gray-600 uppercase tracking-widest">Designed for scale // global connectivity</span>
          </div>
        </div>

        <div className="grid md:grid-cols-4 gap-6">
          <MarketCard 
            icon={Rocket}
            title="Founders"
            description="Pitch, strategize, and build with AI that tracks every pivot and decision you make in the room."
            colorClass="bg-gradient-to-br from-blue-500 to-cyan-400"
          />
          <MarketCard 
            icon={Zap}
            title="Creators"
            description="Host brainstorms, generate visuals live, and instantly share the best clips to your community."
            colorClass="bg-gradient-to-br from-purple-500 to-pink-500"
          />
          <MarketCard 
            icon={Users}
            title="Teams"
            description="Automatic transcripts and action item tracking means you spend less time on syncs and more on shipping."
            colorClass="bg-gradient-to-br from-green-500 to-emerald-400"
          />
          <MarketCard 
            icon={GraduationCap}
            title="Students"
            description="Turn lecture calls into searchable notes and study guides automatically generated by the Aether core."
            colorClass="bg-gradient-to-br from-orange-500 to-red-400"
          />
        </div>
      </div>
    </section>
  );
};

export default TargetMarkets;
